config/routes.rb
Rails.application.routes.draw do

  get 'payments/new'

  get 'orders/show'

  ActiveAdmin.routes(self)
  devise_for :users, only: :omniauth_callbacks, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  scope '(:locale)', locale: /fr|en/ do
    devise_for :users, skip: :omniauth_callbacks

    root to: 'pages#home'
    get "inspiration", to: "pages#inspiration", as: 'inspiration'
    resources :users, only: [:edit, :update]
    get "profile", to: "users#show", as: 'profile'

    get "cart", to: "carts#show", as: 'cart'

    resources :carts, only: [:destroy] do
      collection do
       post "add_item"
       post "remove_item"
       post "clear_cart"
      end
    end
    post "add_item", to: "carts#add_item", as: 'add_item_cart'
    post "remove_item", to: "carts#remove_item", as: 'remove_item_cart'

    resources :balconies, except: [:show] do
      resources :reviews, only: :create
      member do
        post "add_item"
        post "remove_item"
        post "add_collection_to_cart"
      end
    end

    get "balconies_private/:id", to: "balconies#show_private", as: 'private_balcony'
    get "balconies_public/:id", to: "balconies#show_public", as: 'public_balcony'
    get "complete", to: "balconies#complete", as: 'complete'

    resources :items, only: [:index, :show, :destroy] do
      member do
        post "add_plant"
        post "remove_plant"
        post "duplicate"
      end
    end

    resources :orders, only: [:show, :create] do
      resources :payments, only: [:new, :create]
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  mount_uploader :picture, PhotoUploader

  has_many :balconies
  has_many :carts

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  devise :omniauthable, omniauth_providers: [:facebook]

  def self.find_for_facebook_oauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
      user.remote_picture_url = auth.info.image
      user.token = auth.credentials.token
      user.token_expiry = Time.at(auth.credentials.expires_at)
    end
  end

  def cart
    if Cart.where(user_id: self.id).empty? || Cart.where(user: self).last.status
      @cart = Cart.new
      @cart.status = false
      @cart.price = 0
      @cart.user = self
      @cart.save
    else
      @cart = Cart.where(user: self).last
    end
    @cart
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_after_action :verify_authorized
  before_action :set_user, only: [:show, :edit, :update]

  def show
    @balconies = current_user.balconies.all
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to profile_path
      flash[:notice] = "profile successfuly edited"
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :picture, :first_name, :last_name, :created_at)
  end

  def set_user
    @user = current_user
  end
end

app/views/users/edit.html.erb
<!-- BANNER  -->
<section id="toto" class=" navtip module-hero bg-black-alfa-30  color-white parallax " data-background="assets/Sky.jpeg">
  <div class="hero-caption">
    <div class="hero-text m-b-5">
      <div class="container">
        <div class="row">
          <div class="col-sm-12 text-center">
            <h1 class="montserrat text-l m-t-70 m-b-5">Edit your profile information</h1>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<div class="container m-t-60 m-b-60 ">
  <div class="row">
		<div class="col-sm-6 col-sm-offset-3 col-xs-12">
      <%= simple_form_for @user do |f| %>
        <%= f.input :first_name %>
        <%= f.input :last_name %>
        <%= f.input :email %>
        <%= f.input :picture %>
        <%= f.input :picture_cache, as: :hidden %>
        <%= f.submit 'save settings', class: "btn btn-xl btn-round btn-base center-block m-t-40" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<section data-jarallax-original-styles="background-image: url(&quot;<%= image_path('Sky.jpeg')%>&quot;);" style="background-image: none; background-attachment: scroll; background-size: auto auto;" class="module-sm bg-black-alfa-30 color-white parallax" data-background="<%= image_path('Sky.jpeg')%>">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 text-center">
        <h3 class="montserrat text-uppercase m-t-40">Profile page</h3>
      </div>
    </div>
  </div>
</section>

<!-- USER INFORMATION -->
<div class="container m-t-60 m-b-20 ">
  <div class="row">
		<div class="col-sm-4">
      <div class="text-center center">
        <% if !current_user.picture.url %>
          <%= cl_image_tag "avatar_o6wrwd.png", width: 200, height: 200, crop: :fill %>
        <% else %>
          <%= cl_image_tag current_user.picture, height: 200, width: 200, crop: :fill %>
        <% end %>
        <br>
        <br>
        <%= link_to "Edit your profile", edit_user_path(@user), class: "btn btn-outline btn-base" %>
      </div>
    </div>
    <div class="col-sm-8">
      <p><b class = "margin">First_name:</b><%= current_user.first_name %></p><hr>
      <p><b class = "margin">Last_name:</b><%= current_user.last_name %> </p><hr>
      <p><b class = "margin">Mail:</b><%= current_user.email %> </p><hr>
      <p><b class = "margin">Status:</b> Early Pimper </p><hr>
      <p><b class = "margin">joined the team:</b> <%= current_user.created_at %> </p><hr>
      <p><b class = "margin">Description: </b>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    </div>
  </div>
</div>
<!-- END USER INFORMATION -->
<hr>


<!-- BALCONY INFORMATION -->

<% if !Balcony.find_by_user_id(@user) %>
  <div class="container m-t-60 m-b-60">
    <div class="row">
      <div class="col-sm-4 text-center">
        <%= link_to "Create your Balcony", new_balcony_path, class: "btn btn-sm btn-round btn-base"  %>
      </div>
      <div class="col-sm-8">
        <p>You have no balcony referenced yet, <b>click the button to create it.</b> </p>
      </div>
    </div>
  </div>

<% else %>

<div class="container m-t-60 m-b-60">
  <div class="row">
		<div class="col-sm-4">
      <div class="text-center center">
        <% balcony = Balcony.where(user: current_user).last %>
        <%= cl_image_tag balcony.photo, height: 200, width: 200, crop: :fill %>
        <br>
        <%= link_to "Edit   your balcony", complete_path, class: "btn btn-outline btn-base" %>
        <br>
        <br>
        <%= link_to "Delete your balcony", balcony_path(balcony), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-outline btn-danger", style: "width: 180px;" %>
      </div>
    </div>
    <div class="col-sm-8">
      <p><b class = "margin">Your balcony name:</b><%= Balcony.find_by_user_id(@user).name %></p><hr>
      <p><b class = "margin">address</b><%= Balcony.find_by_user_id(@user).address %> </p><hr>
      <p><b class = "margin">orientation:</b><%= Balcony.find_by_user_id(@user).orientation %> </p><hr>
      <p><b class = "margin">department:</b> <%= Balcony.find_by_user_id(@user).department %> </p><hr>

      <br>
      <br>
    </div>
  </div>
</div>
<% end %>

<!-- END BALCONY INFORMATION -->
<hr>
<!-- ORDER INFORMATION -->
<% unless Order.where(user_id: current_user.id).empty? %>
  <div class="container m-t-60 m-b-60">
    <div class="row">
  		<div class="col-sm-4">
        <h1>YOUR ORDERS</h1>
        <br>
          <div class="col-sm-8">
            <div class="container">
              <table class="table">
                <thead>
                  <tr>
                    <th>#</th>
                    <th>Order reference</th>
                    <th>date</th>
                    <th>items</th>
                    <th>amount</th>
                    <th>state</th>
                    <th>delivery</th>
                    <th colspan="3"></th>
                  </tr>
                </thead>

                <% count = 0 %>
                <% Order.where(user_id: current_user.id).all.each do |order| %>
                  <% count += 1 %>
                  <tbody>
                    <tr>
                      <td><%= count %></td>
                      <td><%= order.id%></td>
                      <td><%= order.created_at%> </td>
                      <td>Awesome stuff</td>
                      <td><%= order.amount%></td>
                      <td><%= order.state %></td>
                      <td>pending</td>
                    </tr>
                  </tbody>
                <% end %>
              </table>
            </div>
          </div>
      </div>
    </div>
  </div>
<% end %>



<!-- END ORDER INFORMATION -->

app/views/users/update.html.erb
<h1>UserController#update</h1>
<p>Find me in app/views/user_controller/update.html.erb</p>