config/routes.rb
Rails.application.routes.draw do

  get 'payments/new'

  get 'orders/show'

  ActiveAdmin.routes(self)
  devise_for :users, only: :omniauth_callbacks, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  scope '(:locale)', locale: /fr|en/ do
    devise_for :users, skip: :omniauth_callbacks

    root to: 'pages#home'
    get "inspiration", to: "pages#inspiration", as: 'inspiration'
    resources :users, only: [:edit, :update]
    get "profile", to: "users#show", as: 'profile'

    get "cart", to: "carts#show", as: 'cart'

    resources :carts, only: [:destroy] do
      collection do
       post "add_item"
       post "remove_item"
       post "clear_cart"
      end
    end
    post "add_item", to: "carts#add_item", as: 'add_item_cart'
    post "remove_item", to: "carts#remove_item", as: 'remove_item_cart'

    resources :balconies, except: [:show] do
      resources :reviews, only: :create
      member do
        post "add_item"
        post "remove_item"
        post "add_collection_to_cart"
      end
    end

    get "balconies_private/:id", to: "balconies#show_private", as: 'private_balcony'
    get "balconies_public/:id", to: "balconies#show_public", as: 'public_balcony'
    get "complete", to: "balconies#complete", as: 'complete'

    resources :items, only: [:index, :show, :destroy] do
      member do
        post "add_plant"
        post "remove_plant"
        post "duplicate"
      end
    end

    resources :orders, only: [:show, :create] do
      resources :payments, only: [:new, :create]
    end
  end
end

app/views/shared/_banner.html.erb
<!-- HERO -->
  <section id="hero" class="module-hero bg-black-alfa-30 color-white fullheight parallax" data-background="<%= image_path('banner.jpeg')%>">
    <!-- HERO TEXT -->
    <div class="hero-caption">
      <div class="hero-text">
        <div class="container">
          <div class="row">
            <div class="col-sm-12 text-center">
              <h1 class="montserrat text-uppercase text-super-xl m-t-80">PIMP MY BALCONY</h1>
              <h2 class="montserrat text-uppercase text-xl">" Y'a du monde au balcon "</h2>
              <div class="btn-list m-t-45">
                <!-- <a href="#about" class="btn btn-base btn-lg video-pop-up smoothscroll">Create your Balcony</a> -->
                <%= link_to "Create your Balcony", new_balcony_path, class: "btn btn-base btn-lg"  %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- END HERO -->

app/views/shared/_banner_wagon.html.erb
<div class="banner" style="background-image: url(<%= asset_path 'banner.jpeg' %>) ">
  <div class="banner-content">
    <h1>Pimp My Balcony</h1>
    <p>Y'a du monde au balcon</p>
    <%= link_to "Create your Balcony", new_balcony_path , {class: "btn btn-lg btn-success"} %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-brand" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-danger" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<!-- FOOTER -->
<section class="module-xs bg-white-dark m-t-40">
			<div class="container">

				<div class="row multi-columns-row">

					<!-- ICONBOX -->
					<div class="col-sm-3 col-md-3 col-lg-3">
						<div class="box-icon-left">
							<div class="icon-box-icon">
								<i class="fa fa-smile-o"></i>
							</div>
							<h4>Satisfied or refund</h4>
							<p>You may return all or a part of your order within 14 days of receiving it. You will be reimbursed for returned products within 14 days following our receipt of the products.</p>
						</div>
					</div>
					<!-- END ICONBOX -->

					<!-- ICONBOX -->
					<div class="col-sm-3 col-md-3 col-lg-3">
						<div class="box-icon-left">
							<div class="icon-box-icon">
								<i class="fa fa-truck"></i>
							</div>
							<h4>Worldwide Delivery</h4>
							<p>We deliver straight away to the 6 continents : Europe, Asia, Africa, Antarctica, America, Australia thanks to our local partners.</p>
						</div>
					</div>
					<!-- END ICONBOX -->

					<!-- ICONBOX -->
					<div class="col-sm-3 col-md-3 col-lg-3">
						<div class="box-icon-left">
							<div class="icon-box-icon">
								<i class="fa fa-credit-card"></i>
							</div>
							<h4>Secured payment</h4>
							<p>Simple, secure and reliable payment solution. Process payments securely through our website using our reliable payment gateway.</p>
						</div>
					</div>
					<!-- END ICONBOX -->

					<!-- ICONBOX -->
					<div class="col-sm-3 col-md-3 col-lg-3">
						<div class="box-icon-left">
							<div class="icon-box-icon">
								<i class="fa fa-pagelines"></i>
							</div>
							<h4>Furniture recycling</h4>
							<p>We are happy to take your existing oudoor equipment away for you, when we deliver your new purchase for a non-profit fee.<!-- We have partnered with a number of charity organisations who will try to give your old furniture a new life with local families in need of some support. In the case that any item is not reusable, -->It will be disassembled and recycled with the lowest environmental impact.
</p>
						</div>
					</div>
					<!-- END ICONBOX -->

				</div>

			</div>
		</section>


		<footer class="footer">
			<div class="container">
				<div class="row">
					<div class="col-sm-3">
						<div class="widget">
							<div class="counter p-0 m-b-30">
								<h2 class="montserrat m-b-5">
									<span class="counter-timer" data-from="0" data-to="2500">0</span>
								</h2>
								<h5>Fans on Facebook</h5>
							</div>
							<p> Pimp my balcony aims at blooming your urban life by offering appropriate product to turn your balcony into an intimate breathing space. </p>
              <div>
                <ul class="social-icons social-icons-simple">
                  <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                  <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                  <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                </ul>
              </div>
						</div>
					</div>
					<!--  -->

					<!-- Pinterest WIDGET -->
					<div class="col-sm-3">
						<div class="widget">
							<h6 class="montserrat text-uppercase bottom-line">Pinterest inspiration</h6>
            <a data-pin-do="embedBoard" data-pin-lang="fr" data-pin-board-width="400" data-pin-scale-height="240" data-pin-scale-width="100" href="https://www.pinterest.com/pimpmybalco0551/pimp-my-balcony/"></a>
						</div>
					</div>
					<!-- END TWITTER WIDGET -->

					<!-- RECENT POSTS WIDGET -->
					<div class="col-sm-3">
						<div class="widget">
							<h6 class="montserrat text-uppercase bottom-line">New balcony pimpers</h6>
							<ul class="recent-posts">
								<li>
									<div class="widget-posts-image">
										<%= image_tag "yann.jpg" %>
									</div>
									<div class="widget-posts-body">
										<h6 class="widget-posts-title"><%= link_to "Little urban gardener", public_balcony_path(Balcony.first)%></h6>
										<div class="widget-posts-meta">June 24, 2016 </div>
									</div>
								</li>
								<li>
									<div class="widget-posts-image">
										<%= image_tag "fx.jpg" %>
									</div>
									<div class="widget-posts-body">
										<h6 class="widget-posts-title"><%= link_to "The grasshopper", public_balcony_path(Balcony.second)%>
                    </h6>
										<div class="widget-posts-meta">June 22, 2016 </div>
									</div>
								</li>
								<li>
									<div class="widget-posts-image">
										<%= image_tag "alexq.png" %>
									</div>
									<div class="widget-posts-body">
										<h6 class="widget-posts-title"><%= link_to "Flower power guy", public_balcony_path(Balcony.third)%></h6>
										<div class="widget-posts-meta">June 20, 2015 </div>
									</div>
								</li>
							</ul>
						</div>
					</div>
					<!-- END RECENT POSTS WIDGET -->

					<!-- CONTACT WIDGET -->
					<div class="col-sm-3">
						<div class="widget">
							<h6 class="montserrat text-uppercase bottom-line">Contact Us</h6>
							<address class="map-background">
								<p>EuraTechnologies, 165 Avenue de Bretagne, 59000 Lille</p>
								Phone: 0 800 123 4567<br>
								E-mail: <a href="mailto:pimpmybalcony@gmail.com">hello@pimpmybalcony.com</a>
							</address>
						</div>
					</div>
					<!-- END CONTACT WIDGET -->

				</div><!-- .row -->

				<div class="copyright">

					<div class="row">

						<div class="col-sm-6">
							<p class="m-0">
								Copyright <a href="#">Neomax</a>, 2015, All Rights Reserved.
							</p>
						</div>

						<div class="col-sm-6">
							<div class="text-right">
								<a href="#top" class="scroll-top"><i class="fa fa-level-up"></i></a>
							</div>
						</div>

					</div><!-- .row -->

				</div>

			</div>
		</footer>
		<!-- END FOOTER -->

app/views/shared/_navbar.html.erb
<!-- HEADER -->
<header class="header header-fixed header-transparent">
  <div class="container">

    <!-- YOUR LOGO HERE -->
    <div class="inner-header">
      <%= link_to image_tag("icon.png", class: "inner-brand brand-light", id: "logo" , style: "width: 80"), root_path %>
    </div>

    <!-- OPEN MOBILE MENU -->
    <div class="main-nav-toggle">
      <div class="nav-icon-toggle" data-toggle="collapse" data-target="#custom-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </div>
    </div>

    <!-- WIDGETS MENU -->
    <div class="inner-header pull-right">
      <div class="menu-extras clearfix">

        <!-- SHOP CART -->
        <div class="menu-item">
          <div class="extras-cart">
            <%= link_to cart_path, id:"open-cart" do %>
              <i class="icon-basket icons"></i>
              <% if current_user %>
                <span class="cart-badge"><%= @cart.items.size%></span>
              <% end %>
            <% end %>
            </a>
          </div>
        </div>
        <!-- END SHOP CART -->

        <!-- SEARCH -->
        <div class="menu-item hidden-xxs">
          <div class="extras-search">
            <a id="modal-search" href="#"><i class="icon-magnifier icons"></i></a>
            <form action="#" class="header-search-form">
              <div class="search-form-inner">
                <div class="container">
                  <div class="row">
                    <div class="col-sm-12">
                      <div class="header-search-form-clouse">
                        <a href="#" class="form-close-btn">✕</a>
                      </div>
                    </div>
                    <div class="col-sm-12">
                      <input type="text" placeholder="Type &amp; hit enter">
                    </div>
                  </div>
                </div>
              </div>
            </form>
          </div>
        </div>
        <!-- END SEARCH -->

      </div>
    </div>


    <!-- MAIN MENU -->
    <nav id="custom-collapse" class="main-nav collapse clearfix">
      <ul class="inner-nav pull-right">
        <li> <%= link_to 'Inspiration', inspiration_path %> </li>
        <li> <%= link_to 'Product', items_path %> </li>
        <li> <%= link_to 'Profile', profile_path %> </li>
        <% if current_user %>
          <% if current_user.admin %>
            <li> <%= link_to 'Admin', admin_root_path %> </li>
          <% end %>
        <% end %>
        <!-- LOGIN  -->
        <% if user_signed_in? %>
        <li class="has-submenu">
          <%= link_to '#' do %>
              <% if !current_user.picture.url %>
                <%= cl_image_tag "avatar_o6wrwd.png", width: 200, height: 200, crop: :fill, class: "avatar" %>
              <% else current_user.picture %>
                <%= cl_image_tag current_user.picture, height: 200, width: 200, crop: :fill, class: "avatar" %>
              <% end %>
          <% end %>

          <ul class="submenu">
            <li>
              <%= link_to profile_path do %>
                <i class="fa fa-user"></i> <%= t ".profile", default: "Profile" %>
              <% end %>
            </li>
            <li>
              <%= link_to root_path do %>
                <i class="fa fa-home"></i>  <%= t ".profile", default: "Home" %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Log out" %>
              <% end %>
            </li>
          </ul>
        </li>

        <% else %>
          <li>
            <%= link_to 'Login', new_user_session_path %>
          </li>
        <% end %>
        <!-- END LOGIN  -->

      </ul>
    </nav>

  </div>
</header>

<!-- END HEADER -->

app/views/shared/_navbar_wagon.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "icon.png" %>
  <% end %>

  <%= link_to "Inspiration", inspiration_path, class: "navbar-wagon-item navbar-wagon-link" %>
  <%= link_to "Products", items_path, class: "navbar-wagon-item navbar-wagon-link" %>



  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
    <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form>



    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <!-- Notification -->
      <!-- <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>
        <div class="badge-container">
          <i class="fa fa-envelope-o"></i>
          <div class="badge badge-blue">3</div>
        </div>
      <% end %> -->

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag current_user.picture, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "profile" do %>
                <i class="fa fa-user"></i> <%= t ".profile", default: "Profile" %>
              <% end %>
            </li>
            <li>
              <%= link_to root_path do %>
                <i class="fa fa-home"></i>  <%= t ".profile", default: "Home" %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Log out" %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>

    <!-- Button (call-to-action) -->
    <%= link_to t(".top_call_to_action", default: "Post stuff"), "#", class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>