config/routes.rb
Rails.application.routes.draw do

  get 'payments/new'

  get 'orders/show'

  ActiveAdmin.routes(self)
  devise_for :users, only: :omniauth_callbacks, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  scope '(:locale)', locale: /fr|en/ do
    devise_for :users, skip: :omniauth_callbacks

    root to: 'pages#home'
    get "inspiration", to: "pages#inspiration", as: 'inspiration'
    resources :users, only: [:edit, :update]
    get "profile", to: "users#show", as: 'profile'

    get "cart", to: "carts#show", as: 'cart'

    resources :carts, only: [:destroy] do
      collection do
       post "add_item"
       post "remove_item"
       post "clear_cart"
      end
    end
    post "add_item", to: "carts#add_item", as: 'add_item_cart'
    post "remove_item", to: "carts#remove_item", as: 'remove_item_cart'

    resources :balconies, except: [:show] do
      resources :reviews, only: :create
      member do
        post "add_item"
        post "remove_item"
        post "add_collection_to_cart"
      end
    end

    get "balconies_private/:id", to: "balconies#show_private", as: 'private_balcony'
    get "balconies_public/:id", to: "balconies#show_public", as: 'public_balcony'
    get "complete", to: "balconies#complete", as: 'complete'

    resources :items, only: [:index, :show, :destroy] do
      member do
        post "add_plant"
        post "remove_plant"
        post "duplicate"
      end
    end

    resources :orders, only: [:show, :create] do
      resources :payments, only: [:new, :create]
    end
  end
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  monetize :price_cents

  belongs_to :user
  has_and_belongs_to_many :items

  def add_item(item)
    self.items << item
    self.price += item.price
  end

  def remove_item(item)
    # This code is absolute shit, sorry.
    collection = self.items.to_a
    id = collection.index(item)
    collection.delete_at(id)
    self.items.clear
    self.items = collection
    self.price -= item.price
  end

  def remove_all_items
    self.items.clear
    self.price_cents = 0
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:destroy, :add_item, :remove_item, :clear_cart]


  def add_item
    @item = Item.find(params[:item])
    @cart.add_item(@item)

    if @cart.save
      render json: @item
      flash[:notice] = "Item added to your cart"
    else
      redirect_to items_path
      flash[:alert] = "Item not added to your cart"
    end
  end

  def remove_item
    @item = Item.find(params[:item])
    @cart.remove_item(@item)

    if @cart.save
      render json: @item
      flash[:notice] = "Item removed from your cart"
    else
      flash[:alert] = "Item not removed to your cart"
    end
  end

  def clear_cart
    @cart.remove_all_items
    @cart.save
    render json: @cart
  end

  def destroy
    @cart.destroy
  end

  private

  def set_cart
    @cart = Cart.where(user_id: current_user.id).where(status: false).last
    authorize @cart
    return @cart
  end
end

app/views/carts/_show.html.erb
<div class="off-canvas-cart">
  <p class = 'text-center' style ="margin-top: 10px;"> Your cart </p>

    <div style="margin-right: -10px;" class="off-canvas-cart-wrapper">

      <div class="off-canvas-cart-header">
        <a id="cart-toggle" href="#">
          <i class="icon-arrow-right-circle icons"></i>
        </a>
      </div>

      <% if @cart.items.empty? %>
        <div class="row">
          <div class="text-center center-block">
            <hr>
            <p class= "text-center"> Your cart is empty </p>
            <%= link_to "Create your Balcony", new_balcony_path, class: "btn btn-sm btn-round btn-base"  %>
            <br>
            <p> or </p>
            <%= link_to "go shopping", items_path, class: "btn btn-sm btn-round btn-base"  %>
            <br>
            <hr>
          </div>
        </div>

      <% else %>
        <div class="off-canvas-cart-content">
          <div class="off-canvas-cart-content-wrap">
            <% @cart.items.each do |item| %>
              <!-- ITEM -->
              <div class="off-canvas-cart-item" data-id="<%= item.id %>">

                <div class="off-canvas-cart-item-trash">

                  <%= link_to(remove_item_carts_path(item: item.id), html_options = { method: :post, class: "dynamic-remove-item-cart",remote: true }) do %>
                    <i class="fa fa-trash-o" aria-hidden="true"></i>
                  <% end %>
                </div>

                <div class="off-canvas-cart-item-thumbnail">
                  <%= link_to item_path(item) do %>
                    <%= cl_image_tag item.photo, class: "cart-thumbnail", height: 400, width: 400, crop: :fill %>
                  <% end %>
                </div>

                <div class="off-canvas-cart-item-title">
                  <%= link_to item_path(item) do %>
                    <h5 class="m-b-5"> <%= item.name %> </h5>
                  <% end %>
                    <span><%= humanized_money_with_symbol(item.price) %></span>
                </div>

              </div>
            <% end %>
            <!-- END ITEM -->
          </div>

          <div class="off-canvas-cart-footer">

            <div class="off-canvas-cart-info">
              <div class="row">
                <div class="col-xs-6">
                  <h4 class="m-0">Total:</h4>
                </div>
                <div class="col-xs-6">
                  <h4 class="m-0 text-left"><%= humanized_money_with_symbol(@cart.price) %></h4>
                </div>
              </div>
            </div>

            <div class="off-canvas-cart-control">

              <%= link_to "clear cart", clear_cart_carts_path, method: :post, class: 'btn btn-sm btn-circle btn-dark dynamic-clear-cart', remote: true %>
              <%= form_tag orders_path do %>
                <%= hidden_field_tag 'cart_id', @cart.id %>
                <%= submit_tag 'Checkout', class: 'btn btn-lg btn-block btn-round btn-base' %>
              <% end %>
            </div>

          </div>
        </div>
    <% end %>

  </div>
</div>