config/routes.rb
Rails.application.routes.draw do

  get 'payments/new'

  get 'orders/show'

  ActiveAdmin.routes(self)
  devise_for :users, only: :omniauth_callbacks, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  scope '(:locale)', locale: /fr|en/ do
    devise_for :users, skip: :omniauth_callbacks

    root to: 'pages#home'
    get "inspiration", to: "pages#inspiration", as: 'inspiration'
    resources :users, only: [:edit, :update]
    get "profile", to: "users#show", as: 'profile'

    get "cart", to: "carts#show", as: 'cart'

    resources :carts, only: [:destroy] do
      collection do
       post "add_item"
       post "remove_item"
       post "clear_cart"
      end
    end
    post "add_item", to: "carts#add_item", as: 'add_item_cart'
    post "remove_item", to: "carts#remove_item", as: 'remove_item_cart'

    resources :balconies, except: [:show] do
      resources :reviews, only: :create
      member do
        post "add_item"
        post "remove_item"
        post "add_collection_to_cart"
      end
    end

    get "balconies_private/:id", to: "balconies#show_private", as: 'private_balcony'
    get "balconies_public/:id", to: "balconies#show_public", as: 'public_balcony'
    get "complete", to: "balconies#complete", as: 'complete'

    resources :items, only: [:index, :show, :destroy] do
      member do
        post "add_plant"
        post "remove_plant"
        post "duplicate"
      end
    end

    resources :orders, only: [:show, :create] do
      resources :payments, only: [:new, :create]
    end
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
  monetize :price_cents
  mount_uploader :photo, PhotoUploader

  has_and_belongs_to_many :balconies
  has_and_belongs_to_many :plants
  has_and_belongs_to_many :carts

  validates :name, presence: true
  validates :description, presence: true
  validates :category, inclusion: { in: %w(Deco Pot Plant Custom)}
  validates :price, presence: true

  def add_plant(plant)
    self.plants << plant
    self.price_cents += plant.price_cents
  end

  def remove_plant(plant)
    # This code is absolute shit, sorry.
    collection = self.plants.to_a
    id = collection.index(plant)
    collection.delete_at(id)
    self.plants.clear
    self.plants = collection
    self.price_cents -= plant.price_cents

  end

  def remove_all_plants
    self.plants.clear
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  skip_after_action :verify_authorized
  before_action :set_item, only: [:add_plant, :remove_plant, :duplicate, :destroy]

  def index
    @items = policy_scope(Item)
  end

  def show
    @item = Item.find(params[:id])
    authorize @item
  end

  def destroy
    @item.destroy
    redirect_to complete_path
  end

  def duplicate
    my_pot = Item.new({
                    name: params[:name].to_s + '\' s pot',
                    category: "Custom",
                    description: "to do",
                    price: @item.price,
                    slot: @item.slot,
                    volume: @item.volume,
                    length: @item.length,
                    width: @item.width,
                    weight: @item.weight
                    })
    my_pot.remote_photo_url = @item.photo.to_s
    if my_pot.save
      render json: my_pot
    else
      redirect_to complete_path
    end
  end

  def add_plant
    if @item.plants.size < @item.slot
      @plant = Plant.find(params[:plant])
      @item.add_plant(@plant)

      if @item.save
        render json: @item
        flash[:notice] = "Plant added to your item"
      else
        redirect_to complete_path
        flash[:alert] = "Plant not added to your item"
      end
    else
      flash[:alert] = "No room left in this pot, pick another one !"
      redirect_to complete_path
    end
  end

  def remove_plant
    @plant = Plant.find(params[:plant])
    @item.remove_plant(@plant)

    if @item.save
      render json: @item
      flash[:notice] = "Plant removed from your item"
    else
      redirect_to complete_path
      flash[:alert] = "Item not removed to your item"
    end
  end

  private

  def set_item
    @item = Item.find(params[:id])
    authorize @item
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/index.html.erb
<!-- BANNER  -->
<!-- <section id="toto" class=" navtip module-hero bg-black-alfa-30  color-white parallax " data-background="assets/Sky.jpeg">
  <div class="hero-caption">
  </div>
</section> -->

<!-- CARROUSSEL -->
<div class="wrapper">

  <!-- HERO -->
  <div class="flexslider color-white">
    <ul class="slides">

      <!--  -->
      <li class="bg-black-alfa-40" style="background-image:url(<%= image_path('Carrousel_1.jpeg')%>)">
        <!-- HERO TEXT -->
        <div class="hero-caption">
          <div class="hero-text">
            <div class="container">
              <div class="row">
                <div class="col-sm-12 text-center">
                  <h1 class="montserrat text-uppercase text-super-xl m-b-40">Awesome items</h1>
                  <h2 class="montserrat text-uppercase text-xl">Adapted to your balcony</h2>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- END HERO TEXT -->
      </li>
      <!--  -->

      <!--  -->
      <li class="bg-black-alfa-40" style="background-image:url(<%= image_path('Carrousel_2.jpeg')%>)">
        <!-- HERO TEXT -->
        <div class="hero-caption">
          <div class="hero-text">
            <div class="container">
              <div class="row">
                <div class="col-sm-12 text-center">
                  <h2 class="montserrat text-uppercase m-b-40">Flower power</h2>
                  <h1 class="montserrat text-uppercase text-super-xl m-b-40"> -20 % on flowers</h1>
                  <p>* by using the coupon code "flower-power", available until july 20th</p>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- END HERO TEXT -->
      </li>
      <!--  -->


      <li class="bg-black-alfa-40" id="tata" style="background-image:url(<%= image_path('Carrousel_3.jpeg')%>)">
        <!-- HERO TEXT -->
        <div class="hero-caption">
          <div class="hero-text">
            <div class="container">
              <div class="row">
                <div class="col-sm-12 text-center">
                  <h2 class="montserrat text-uppercase m-b-40">Get inspired</h2>
                  <h1 class="montserrat text-uppercase text-xxxxxl m-b-40">New Pots</h1>
                  <p>Discover our new range of custom pot for your balcony</p>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- END HERO TEXT -->
      </li>
      <!--  -->
    </ul>
  </div>
  <!-- END HERO -->

  <!-- WRAPPER -->
<div class="wrapper">

  <section class=" m-t-40 bg-white-dark">
    <div class="container">
      <div class="row">
        <div class="col-sm-12 text-center">
          <h3 class="montserrat text-uppercase m-t-40">The balcony boutique</h3>
          <!-- PORTFOLIO FILTERS -->
    			<div class="row">
    				<div class="col-sm-12">
    					<ul id="filters" class="filters p-t-20 bg-white-dark">
    						<li><a href="#" class="current" data-filter="*">All</a></li>
                <li><a href="#" data-filter=".pot">Pot</a></li>
    						<li><a href="#" data-filter=".plant">Plant</a></li>
    						<li><a href="#" data-filter=".deco">Deco</a></li>
    					</ul>
    				</div>
    			</div>
        </div>
      </div>
    </div>
  </section>

  <!-- PORTFOLIO -->
	<section class=" m-t-40 p-b-0">
    <div class="container">

			<!-- WORKS WRAPPER -->
			<div class="works-grid-wrapper">

				<!-- WORKS GRID -->
				<div id="works-grid" class="works-grid works-grid-4">

          <!-- PORTFOLIO ITEM -->
          <% Item.all.each do |item| %>
  					<article class="work-item <%= item.category.downcase %>" style="padding: 20px 20px 40px 20px;">
  						<div class="work-wrapper">
                <%= cl_image_tag item.photo, height: 500, width: 720, crop: :fill %>
  							<div class="work-overlay">
  								<div class="work-caption">
  									<div class="work-title" style="text-align:center;">
                      <h5><%= humanized_money_with_symbol(item.price) %> </h5>
                        <%= link_to(add_item_carts_path(item: item.id),html_options = { method: :post, class: "dynamic-add-to-cart-item", remote: true}) do %>
                            <i class="icon-basket-loaded icons" aria-hidden="true" style="color:white; width: 100px;"></i>
                        <% end %>
                    </div>
                  </div>
                </div>
  						</div>
              <div class="work-title p-t-20" data-id="<%='additem' + item.id.to_s%>" style="text-align:center;">
                <h5><%= link_to item.name, item_path(item.id) %></h5>
              </div>
  					</article>
          <% end %>
					<!-- END PORTFOLIO ITEM -->
				</div>
				<!-- END WORKS GRID -->
			</div>
			<!-- END WORKS WRAPPER -->
		</section>
		<!-- END PORTFOLIO -->
  </div>
  <!-- END WRAPPER -->
</div>

app/views/items/show.html.erb
<section id="toto" class=" navtip module-hero bg-black-alfa-30  color-white parallax " data-background="assets/Sky.jpeg">
  <div class="hero-caption">
  </div>
</section>

<!-- WRAPPER -->
<div class="wrapper">

  <!-- PAGE TITLE -->
  <section class="module-sm bg-white-dark">
    <div class="container">

      <div class="row">
        <div class="col-sm-12 text-center">

          <h3 class="montserrat text-uppercase m-b-10">Product details</h3>
          <ol class="breadcrumb text-xs">
            <li><a href="#">Home</a></li>
            <li><a href="#">Shop</a></li>
            <li class="active">Product details</li>
          </ol>

        </div>
      </div>

    </div>
  </section>
  <!-- END PAGE TITLE -->

  <!-- PRODUCT DETAILS -->
  <section class="module-sm divider-bottom">
    <div class="container">

      <div class="row">

        <!-- PRODUCT SLIDER -->
        <div class="col-sm-7">
          <div class="product-slider">
            <div class="item"><%= cl_image_tag @item.photo, height: 400, width: 600, crop: :fill %> </div>
            <div class="item"><img src="assets/images/shop/13-2.jpg" alt=""></div>
            <div class="item"><img src="assets/images/shop/13-3.jpg" alt=""></div>
            <div class="item"><img src="assets/images/shop/13-4.jpg" alt=""></div>
          </div>
        </div>
        <!-- END PRODUCT SLIDER -->

        <div class="col-sm-5">
          <div class="product-description m-b-30">
            <h2 class="m-b-5"><%= @item.name %></h2>
            <span class="star-rating star-rating-4"></span>
            <a href="#" class="text-xs">2 customer reviews</a>
          </div>
          <div class="m-b-30">
            <h2 class="montserrat">
              <span class="sale-text"> <%= (@item.price)*0.9 %> </span>
              <%= @item.price %>
            </h2>
          </div>
          <hr class="m-t-30 m-b-30">
          <p> <%= @item.description %></p>
          <p>Tags:
            <%= link_to @item.category, items_path %>  -
            <%= link_to @item.sub_category, items_path %>  -
            <%= link_to @item.plant_category, items_path %>
          </p>
          <hr class="m-t-30 m-b-30">

          <!-- PRODUCT FORM -->
          <form method="post">
            <div class="row">
              <div class="col-sm-6">
                <div class="form-group">
                  <label class="sr-only">Quantity</label>
                  <input type="number" class="form-control" step="1" min="1" value="1">
                </div>
              </div>

              <div class="col-sm-6">
                <div class="form-group">
                  <label class="sr-only">Size</label>
                  <select class="form-control">
                    <option selected="selected" disabled>Size</option>
                    <option value="xxs">xs</option>
                    <option value="xs">s</option>
                    <option value="s">m</option>
                  </select>
                </div>
              </div>
            </div><!-- .row -->

            <div class="row">
              <div class="col-sm-6">
                <a class="btn btn-block btn-round btn-base">Add to cart</a>
              </div>
            </div><!-- .row -->
          </form>
          <!-- END PRODUCT FORM -->

        </div>
      </div><!-- .row -->

      <div class="row m-t-70">
        <div class="col-sm-12">

          <!-- TABS NAV-->
          <ul class="nav-text-tabs">
            <li class="active"><a href="#description" data-toggle="tab">Description</a></li>
            <li><a href="#data-sheet" data-toggle="tab">requirements</a></li>
            <li><a href="#reviews" data-toggle="tab">Reviews</a></li>
          </ul>
          <!-- END TABS NAV-->

          <!-- TAB CONTENT -->
          <div class="tab-content">

            <div id="description" class="tab-pane active">
              <p><%= @item.description %></p>
            </div>

            <div id="data-sheet" class="tab-pane">
              <table class="table table-striped">
                <tbody>
                  <tr>
                    <th>Length</th>
                    <th><%= @item.length %> cm</th>
                  </tr>
                  <tr>
                    <td>Width</td>
                    <td><%= @item.width %> cm</td>
                  </tr>
                  <tr>
                    <td>Volume</td>
                    <td><%= @item.volume %> L</td>
                  </tr>
                  <tr>
                    <td>Weight</td>
                    <td><%= @item.weight%> Kg</td>
                  </tr>
                </tbody>
              </table>
            </div>

            <div id="reviews" class="tab-pane">
              <!-- REVIEWS -->
              <div class="comments reviews">
                <div class="comment">
                  <div class="comment-content">
                    <h5><a href="#">Michael Thomas</a></h5>
                    <p>Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus.</p>
                    <span class="star-rating star-rating-4"></span>
                  </div>
                </div>

                <div class="comment">
                  <div class="comment-content">
                    <h5><a href="#">Adam Hines</a></h5>
                    <p>Nam adipiscing. Vestibulum eu odio. Vivamus laoreet. Nullam tincidunt adipiscing enim. Phasellus tempus. Proin viverra, ligula sit amet ultrices semper, ligula arcu tristique sapien, a accumsan nisi mauris ac eros.</p>
                    <span class="star-rating star-rating-5"></span>
                  </div>
                </div>
              </div>
              <!-- END REVIEWS -->

              <!-- REVIEW FROM -->
              <form method="post">
                <div class="row">
                  <div class="col-sm-4">
                    <div class="form-group">
                      <label class="sr-only" for="name">Name</label>
                      <input type="text" id="name" class="form-control" name="name" placeholder="Name">
                    </div>
                  </div>
                  <div class="col-sm-4">
                    <div class="form-group">
                      <label class="sr-only" for="email">Name</label>
                      <input type="text" id="email" class="form-control" name="email" placeholder="E-mail">
                    </div>
                  </div>
                  <div class="col-sm-4">
                    <div class="form-group">
                      <select class="form-control">
                        <option>Select one</option>
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                        <option value="5">5</option>
                      </select>
                    </div>
                  </div>
                  <div class="col-sm-12">
                    <div class="form-group">
                      <textarea class="form-control" rows="4" placeholder="Review"></textarea>
                    </div>
                  </div>
                  <div class="col-sm-12">
                    <button type="submit" class="btn btn-round btn-base">Submit Review</button>
                  </div>
                </div>
              </form>
              <!-- END REVIEW FROM -->
            </div>

          </div>
          <!-- END TAB CONTENT -->

        </div>
      </div><!-- .row -->

    </div>
  </section>
  <!-- END PRODUCT DETAILS -->

  <!-- RELATED PRODUCTS -->
  <section class="module">
    <div class="container">

      <div class="row">
        <div class="col-sm-12">
          <h5 class="montserrat text-uppercase bottom-line">Related Products</h5>
        </div>
      </div>

      <div class="row multi-columns-row">

        <% Item.where(category: @item.category).first(4).each do |product| %>
        <div class="col-sm-3 col-md-3 col-lg-3">
          <div class="shop-item">
            <div class="shop-item-photo">
              <%= cl_image_tag product.photo, height: 400, width: 720, crop: :fill %>
              <div class="shop-item-tools">
                <div>
                  <div>
                    <%= link_to item_path(product.id) do %>
                        <i class="fa fa-eye" aria-hidden="true"></i>
                    <% end %>
                    <%= link_to items_path do %>
                        <i class="icon-basket-loaded icons" aria-hidden="true"></i>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
            <div class="shop-item-title">
              <h5><%= link_to product.name, item_path(product.id) %></h5>
              <h5><%= product.price %>,00 € </h5>
            </div>
          </div>
        </div>
        <% end %>
        <!-- END SHOP ITEM -->

      </div>
    </div>
  </section>
  <!-- END RELATED PRODUCTS -->

</div>
<!-- END WRAPPER -->